### PR TITLE
Support the React 0.14 betas

### PR DESCRIPTION
**Pull request by jarib**
I'd like to use react-spinkit with the current betas. Fingers crossed for a quick release :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Why is this PR necessary? Does spinkit not install?

**Comment by jarib** [comment]
Correct:

```console
$ npm install
npm WARN package.json foo@1.0.0 No description
npm WARN package.json foo@1.0.0 No repository field.
npm WARN package.json foo@1.0.0 No README data
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/opt/boxen/nodenv/versions/0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.13.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.0-beta3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-spinkit@1.1.2 wants react@>=0.12.0

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/foo/npm-debug.log
$
```

**Comment by KyleAMathews** [comment]
So `peerDependencies` is even more annoying than I thought :) I just went ahead and removed it because there's nothing in this module that should break in different versions of React.

https://github.com/KyleAMathews/react-spinkit/commit/50e32c49d39281105e36ac81045ddff79168a7f3

**Comment by jarib** [comment]
Thanks!

**Pull request closed without merging**
