### PR TITLE
use currentColor to inherit current font color

### PR DESCRIPTION
**Pull request by hontas**
Make all spinners inherit current set font color

### CODE REVIEW

**Comment by hontas** [comment]
made a pull request to spinkit instead. cheers!

**Comment by KyleAMathews** [comment]
:+1: 

If he doesn't update soon, let me know and I'll just merge this!

**Comment by merrywhether** [comment]
@hontas This was used as inspiration for what has become 3.0

**Comment by hontas** [comment]
Cool :)

**Pull request closed without merging**
