### PR TITLE
added sk- prefix to css class names

### PR DESCRIPTION
**Pull request by carlos-stored**
@KyleAMathews

### CODE REVIEW

**Comment by carlos-stored** [comment]
@KyleAMathews

**Comment by KyleAMathews** [comment]
@carlos-stored somehow I missed this! This looks like a smart idea. It'd be a breaking change but namespacing CSS is unfortunately fairly necessary.

If you're still interested in the PR, feel free to fix it up and I'll make a release.

**Comment by kkozee** [comment]
@KyleAMathews I've never made an open source contribution but my team could use this PR for a production app that uses another generic `.circle` class.  I forked your project, branched off @carlos-stored master, rebased to your master and updated `index.jsx`. Is that okay protocol for me to open a PR or are there other steps I should take? Thanks for the great project!

**Comment by KyleAMathews** [comment]
@kkozee yeah, that'd be great! Just push your changes to Github and create the PR!

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/KyleAMathews/react-spinkit/pull/49

**Pull request closed without merging**
