### PR TITLE
Add cssify transform

### LINKED ISSUE #9: Browserify complains about CSS
I'm getting this from my Grunt Browserify output.  Are these files really CSS or do they need some sort of preprocessing?

```
>> /Users/me/project/node_modules/react-spinkit/css/fade-in.css:1
>> @-webkit-keyframes fade-in {
>> ^
>> ParseError: Unexpected character '@'
```

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes #9

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I'm not super familiar with Browserify — should cssify be a devDependency or a regular dependency as you have it?

**Comment by blakeembrey** [comment]
It won't install as a `devDependency` when you do `npm install`.

**Comment by KyleAMathews** [comment]
LGTM

**Comment by KyleAMathews** [comment]
Thanks! Published a 0.7.0 with your changes.

**Pull request merged**
